// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace Spelling.Data.Migrations
{
    public partial class AddRelation_User_Table_BestScores : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_BestScores_UserId",
                table: "BestScores",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_BestScores_Users_UserId",
                table: "BestScores",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BestScores_Users_UserId",
                table: "BestScores");

            migrationBuilder.DropIndex(
                name: "IX_BestScores_UserId",
                table: "BestScores");
        }
    }
}
