// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace Spelling.Data.Migrations
{
    public partial class AddColumn_CreationDate_Table_BestScore : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "GameCreationDate",
                table: "BestScores",
                type: "datetime",
                nullable: false,
                defaultValue: new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "GameCreationDate",
                table: "BestScores");
        }
    }
}
