//-----------------------------------------------------------------------
// <copyright file="SeedWords.cs" company="Gabriel Castillo">
//     Company copyright tag.
// </copyright>
//-----------------------------------------------------------------------
namespace Spelling.Data.Seeding
{
    using System.Collections.Generic;
    using System.Linq;
    using Spelling.Domain;

    /// <summary>
    /// Seed Words
    /// </summary>
    public static class SeedWords
    {
        /// <summary>
        /// Seeds the specified context.
        /// </summary>
        /// <param name="context">The context.</param>
        public static void Seed(SpellingContext context)
        {
            var list = new List<Word>();

            list.Add(new Word { Spanish = "que tipo", English = "what kind of", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "que clase", English = "what sort of", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "hacia donde", English = "where .. To", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "a quien", English = "whom", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "para quien", English = "who .. For", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "como", English = "how", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "hacia que", English = "what .. At", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "con que", English = "what .. With", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "Con que frecuencia", English = "How often", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "a que hora", English = "at what time", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "como es (descripción)", English = "what .. Look Like", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "de donde", English = "where .. from", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "acerca de que", English = "what .. About", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "para que", English = "what .. For", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "cual", English = "which", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "Cuanto tiempo", English = "How long", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "con quién", English = "Who .. With", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "de quien", English = "Whose", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "acerca de quien", English = "who .. About", GroupType = GroupType.Questions });
            list.Add(new Word { Spanish = "frecuentemente", English = "frequently", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "a menudo", English = "Often", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "ocasionalmente", English = "occasionally", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "siempre", English = "Always", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "nunca", English = "Never", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "normalmente", English = "normally", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "rara vez", English = "rarely", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "una vez", English = "once", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "casi nunca", English = "hardly ever", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "a veces", English = "Sometimes", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "rara vez", English = "seldom", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "usualmente", English = "Usually", GroupType = GroupType.AdverbsOfFrecuency });
            list.Add(new Word { Spanish = "bruto, grosero", English = "gross", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "leve, tenue, vago, ligero", English = "faint", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "suave, leve", English = "mild", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "repugnante, asqueroso, desagradable", English = "nasty", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "fuerte, ruidoso", English = "loud", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "dolorido", English = "sore", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "torpe", English = "clumsy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "grueso, ordinario, tosco", English = "coarse", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "lujoso", English = "fancy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "grasiento", English = "greasy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "superficial, poco profundo", English = "shallow", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "dificil, resistente, duro", English = "tough", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "inmundo, asqueroso, puerco", English = "filthy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "triste, melancolico, abatido, pesimista", English = "gloomy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "digno, meritorio", English = "worthy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "sudoroso", English = "sweaty", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "raro, extraño", English = "weird", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "rizado, crespo, quebrado", English = "curly", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "codicioso, ávido", English = "greedy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "sediento", English = "thirsty", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "llano, liso, plano", English = "flat", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "fiero, encarnizado", English = "fierce", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "audaz", English = "bold", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "áspero, tosco, bruto, ronco", English = "rough", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "escamoso", English = "flaky", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "viscoso, baboso", English = "slimy", GroupType = GroupType.Adjectives });
            list.Add(new Word { Spanish = "liguero", English = "suspender", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "vestido", English = "dress", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "corbatin", English = "bowtie", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "sudadera", English = "sweatshirt", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "abrigo", English = "coat", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "pantalon", English = "trousers", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "blusa", English = "blouse", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "chaleco", English = "waistcoat", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "corbata", English = "tie", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "sandalias", English = "sandals", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "cordones", English = "laces", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "guantes", English = "gloves", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "bufanda", English = "scarf", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "botas", English = "boots", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "traje", English = "suit", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "pantalones cortos", English = "shorts", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "vestido de baño", English = "swimming costume", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "minifalda", English = "miniskirt", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "sombrero", English = "hat", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "bata", English = "dressing-gown", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "buso de lana", English = "cardigan", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "cremallera", English = "zip", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "camiseta", English = "shirt", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "overol", English = "overall", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "brasier", English = "bra", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "calcetines/medias", English = "socks", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "falda", English = "skirt", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "zapatos", English = "shoes", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "cinturon", English = "belt", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "gorra", English = "cap", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "media velada", English = "stockings", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "tirantes", English = "braces", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "impermeable", English = "raincoat", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "ropa interior(mujer)", English = "knickers", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "chaqueta", English = "jacket", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "calzoncillos", English = "underpants", GroupType = GroupType.Clothes });
            list.Add(new Word { Spanish = "Cadera", English = "Hip", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Riñones", English = "Kidneys", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Párpado", English = "Eyelid", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Costilla", English = "Rib", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Uña", English = "Nail", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Vena", English = "Vein", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Trasero", English = "Bottom", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Codo", English = "Elbow", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Encías", English = "Gums", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Nudillo", English = "Knuckle", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Genitales", English = "Genitals", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Ceja", English = "Eyebrow", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Hombro", English = "Shoulder", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pantorrilla", English = "Calf", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Tobillo", English = "Ankle", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Labio", English = "Lip", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Cintura", English = "Waist", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Hígado", English = "Liver", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Cerebro", English = "Brain", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pierna", English = "Leg", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Puño", English = "Fist", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Mandíbula", English = "Jaw", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Músculo", English = "Muscle", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Cráneo", English = "Skull", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pestaña", English = "Eyelash", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Miembro ; Extremidad", English = "Limb", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Mejilla", English = "Cheek", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Muñeca", English = "Wrist", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Dedo de la mano", English = "Finger", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Articulación", English = "Joint", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Estómago", English = "Stomach", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Brazo", English = "Arm", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pecho", English = "Chest", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Oreja", English = "Ear", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Rodilla", English = "Knee", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Nervio", English = "Nerve", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Ombligo", English = "navel", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Diente/dientes", English = "Tooth/Teeth", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Espina dorsal ; Columna vertebral", English = "Spine", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Arteria", English = "Artery", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pulmón", English = "Lung", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Muslo", English = "Thigh", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Dedo del pie", English = "Toe", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Cuello", English = "Neck", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Barbilla ; Mentón", English = "Chin", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Frente", English = "Forehead", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Talón", English = "stub", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Pie", English = "Foot", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Costado", English = "Side", GroupType = GroupType.Body });
            list.Add(new Word { Spanish = "Contener", English = "Contain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Calentar", English = "Heat", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Obedecer", English = "Obey", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Absolver", English = "Absolve", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Solicitar/requerir", English = "Request", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Incluir", English = "Include", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ocultar", English = "Conceal", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Sufrir", English = "Suffer", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "abusar", English = "Abuse", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mejorar", English = "Improve", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Preguntar/Averiguar", English = "Inquire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Presentar", English = "Present", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Durar", English = "Last", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Referir", English = "Refer", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Precipitarse", English = "Rush", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Volver", English = "Return", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Patear", English = "Kick", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Extraer", English = "Extract", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Suponer", English = "Suppose", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Gobernar", English = "Govern", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Rechazar/Rehusar", English = "Refuse", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Traducir", English = "Translate", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Impresionar", English = "Impress", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ganar", English = "Gain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Disfrutar", English = "Enjoy", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Afirmar", English = "Affirm", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Toser", English = "Cough", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Confiar", English = "Trust", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Poseer", English = "Possess", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Obligar", English = "Oblige", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Terminar", English = "End", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Quejarse", English = "Complain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Combinar", English = "Combine", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Proteger/Guardar", English = "Guard", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Firmar", English = "Sign", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Culpar", English = "Blame", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Desaprobar", English = "Dislike", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Componer", English = "Compose", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ahorrar", English = "Save", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Adquirir", English = "Acquire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Empezar", English = "Start", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Preferir", English = "Prefer", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mirar/Vigilar", English = "Watch", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ofrecer", English = "Offer", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Fallar", English = "Fail", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Caminar", English = "Walk", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acostumbrar", English = "Accustom", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Lavar", English = "Wash", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Dividir", English = "Divide", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Quitar", English = "Remove", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cerrar", English = "Close", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cambiar", English = "Change", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Defender", English = "Defend", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Numerar", English = "Number", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Jugar/Tocar", English = "Play", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Declarar", English = "Declare", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ascender/cantidad", English = "Amount", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Fumar", English = "Smoke", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Contestar", English = "Answer", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Estudiar", English = "Study", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Producir", English = "Produce", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Hablar", English = "Talk", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Dañar", English = "Damage", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Domesticar", English = "Tame", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mover", English = "Move", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mentir", English = "Lie", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Proponer", English = "Propose", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aterrizar", English = "Land", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Recordar", English = "Remind", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Justificar", English = "Justify", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Desarrollar", English = "Develop", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Amar", English = "Love", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acelerar", English = "Accelerate", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Admirar", English = "Admire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Elegir", English = "Elect", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Gustar", English = "Like", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Llevar/cargar", English = "Carry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Parecer", English = "Seem", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Notar", English = "Note", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cansar", English = "Tire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Absorber", English = "Absorb", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Usar", English = "Use", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Trepar", English = "Climb", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Atar", English = "Tie", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Agregar", English = "Add", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Flotar", English = "Float", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ocupar", English = "Occupy", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Requerir", English = "Require", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Alcanzar", English = "Reach", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Besar", English = "Kiss", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ayudar", English = "Help", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Pertenecer", English = "Belong", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Empaquetar", English = "Pack", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acceder", English = "Accede", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Contratar/Alquilar", English = "Hire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Sonreír", English = "Smile", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acceder/Estar de acuerdo", English = "Agree", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cazar", English = "Hunt", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Sorprender", English = "Surprise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Arreglar/Componer", English = "Mend", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Intentar", English = "Try", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Exponer", English = "Expose", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reclamar", English = "Claim", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Conceder", English = "Grant", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Trabajar", English = "Work", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Desear", English = "Desire", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Descansar", English = "Rest", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Peinar", English = "Comb", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Anunciar", English = "Announce", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Disculparse/Excusarse", English = "Apologize", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reducir/Bajar", English = "Lower", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Parar", English = "Stop", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Nombrar", English = "Name", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Abandonar", English = "Abandon", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Implicar", English = "Imply", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reparar", English = "Repair", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Preguntar", English = "Ask", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Asistir/Atender", English = "Attend", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ordenar", English = "Order", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Querer", English = "Want", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Saludar", English = "Greet", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Repetir", English = "Repeat", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Esperar deseo", English = "Hope", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Prometer", English = "Promise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Llamar", English = "Call", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ahorcar", English = "Hang", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Llegar", English = "Arrive", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Dedicar", English = "Devote", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Doblar/plegar", English = "Fold", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Importar", English = "Import", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Atacar", English = "Attack", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Seguir", English = "Follow", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Planchar", English = "Iron", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Preocuparse", English = "Worry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Lograr/Llevar a cabo", English = "Achieve", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Viajar", English = "Travel", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Variar", English = "Vary", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Molestar/Fastidiar", English = "Annoy", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Golpear/Llamar", English = "Knock", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Probar sabor", English = "Taste", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "llorar, gritar", English = "Cry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Devorar", English = "Devour", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Adorar", English = "Adore", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Adornar", English = "Adorn", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Matar", English = "Kill", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Invitar", English = "Invite", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Castigar", English = "Punish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Agradecer", English = "Thank", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Permanecer/Quedarse", English = "Remain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Admitir", English = "Admit", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Sugerir", English = "Suggest", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Esperar", English = "Expect", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Corregir", English = "Correct", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Recordar", English = "Remember", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cesar", English = "Cease", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Recibir", English = "Receive", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Coronar", English = "Crown", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Tocar", English = "Touch", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Llover", English = "Rain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Bailar", English = "Dance", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Girar", English = "Turn", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acabar", English = "Finish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Saltar", English = "Jump", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ir a buscar", English = "Fetch", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Pescar", English = "Fish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Pintar", English = "Paint", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reír", English = "Laugh", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Odiar", English = "Hate", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ganar dinero", English = "Earn", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Arrendar", English = "Rent", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Explicar", English = "Explain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mirar", English = "Look", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Tirar de/Halar", English = "Pull", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "complacer/Agradar", English = "Please", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Ordenar/Mandar", English = "Command", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reservar", English = "Book", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Adivinar/Suponer", English = "Guess", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Arreglar/Organizar", English = "Arrange", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Entrar", English = "Enter", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Herir", English = "Wound", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Desear", English = "Wish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Nombrar/Designar", English = "Appoint", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Casarse", English = "Marry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Secar", English = "Dry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aliviar", English = "Relieve", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Sonar", English = "Sound", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aconsejar", English = "Advise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Preparar", English = "Prepare", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Incluir/Adjuntar/Encerrar", English = "Enclose", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Unir", English = "Join", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Arrastrar", English = "Drag", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Colocar/Poner", English = "Place", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Reunir/Recoger", English = "Gather", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Rogar, pedir", English = "Beg", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Practicar", English = "Practise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Actuar", English = "Act", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acentuar", English = "Accent", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Comparar", English = "Compare", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Dirigirse", English = "Address", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Asombrar/sorprender", English = "Astonish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Considerar", English = "Consider", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Temer", English = "Fear", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aceptar", English = "Accept", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cometer", English = "Commit", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Empujar", English = "Push", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Intercambiar/Cambiar", English = "Exchange", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aumentar", English = "Increase", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Consistir", English = "Consist", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Manejar/Manipular", English = "Handle", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Descubrir", English = "Discover", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Escuchar", English = "Listen", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Encajar/Ajustar", English = "Fit", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Jugar/Arriesgarse", English = "Gamble", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Afilar", English = "Sharpen", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Creer", English = "Believe", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Apresurarse", English = "Hurry", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Permitir", English = "Permit", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Atraer", English = "Attract", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Recoger", English = "Collect", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Despreciar", English = "Despise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Expresar", English = "Express", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Establecer", English = "Establish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Estimar", English = "Esteem", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aprobar", English = "Approve", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Esperar", English = "Wait", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Inventar", English = "Invent", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aparecer", English = "Appear", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Entregar", English = "Deliver", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Dejar caer/soltar", English = "Drop", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Suceder/Ocurrir/Pasar", English = "Happen", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Fijar/Arreglar", English = "Fix", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Intentar", English = "Attempt", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Copiar", English = "Copy", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Bromear", English = "Joke", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Aclarar, limpiar", English = "Clear", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Comprobar", English = "Check", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Anunciar", English = "Advertise", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Bañarse", English = "Bathe", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Informar", English = "Report", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Evitar", English = "Avoid", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Visitar", English = "Visit", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Alentar/Animar/Fomentar", English = "Encourage", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Abrir", English = "Open", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Abolir", English = "Abolish", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mantener", English = "Maintain", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Pesar", English = "weigh", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Amanecer", English = "Dawn", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Continuar", English = "Continue", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acusar", English = "Accuse", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Mencionar", English = "Mention", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Destruir", English = "Destroy", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Divertir", English = "Amuse", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Asegurar", English = "Assure", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Pasar/Aprovar", English = "Pass", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Engañar", English = "Deceive", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Limpiar", English = "Clean", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Imaginar", English = "Imagine", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Decidir", English = "Decide", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Replicar", English = "Reply", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Llenar", English = "Fill", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Navegar", English = "Sail", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Vivir", English = "Live", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Contar", English = "Count", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Acercarse/Enfoque", English = "Approach", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Avanzar/Promover", English = "Advance", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Notar, darse cuenta", English = "Notice", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Probar", English = "Test", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Gritar", English = "Shout", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Perturbar/Molestar", English = "Disturb", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Fundar", English = "Found", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cruzar", English = "Cross", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Estallar", English = "Explode", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Emplear", English = "Employ", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Medir", English = "Measure", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Cubrir", English = "Cover", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Evocar", English = "Evoke", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Permitir", English = "Allow", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "Organizar", English = "Organize", GroupType = GroupType.RegularVerbs });
            list.Add(new Word { Spanish = "traer", English = "BRING,BROUGHT,BROUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "ganar", English = "WIN,WON,WON", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "sudar", English = "SWEAT,SWEAT,SWEAT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "dormir", English = "SLEEP,SLEPT,SLEPT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "volar", English = "FLY,FLEW,FLOWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "escribir", English = "WRITE,WROTE,WRITTEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "soplar", English = "BLOW,BLEW,BLOWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "dejar", English = "LEAVE,LEFT,LEFT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "disparar", English = "SHOOT,SHOT,SHOT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "cabalgar, montar", English = "RIDE,RODE,RIDDEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "pagar", English = "PAY,PAID,PAID", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "sentarse", English = "SIT,SAT,SAT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "coger, tomar", English = "TAKE,TOOK,TAKEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "dar", English = "GIVE,GAVE,GIVEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "dibujar", English = "DRAW,DREW,DRAWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "romper", English = "BREAK,BROKE,BROKEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "prestar", English = "LEND,LENT,LENT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "morder", English = "BITE,BIT,BITTEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "enseñar", English = "TEACH,TAUGHT,TAUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "elegir", English = "CHOOSE,CHOSE,CHOSEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "vender", English = "SELL,SOLD,SOLD", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "elevarse, subir", English = "RISE,ROSE,RISEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "pensar", English = "THINK,THOUGHT,THOUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "nadar", English = "SWIM,SWAM,SWUM", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "ver", English = "SEE,SAW,SEEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "sentir", English = "FEEL,FELT,FELT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "perdonar", English = "FORGIVE,FORGAVE,FORGIVEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "alimentar", English = "FEED,FED,FED", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "decir", English = "SAY,SAID,SAID", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "mostrar, enseñar", English = "SHOW,SHOWED,SHOWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "significar, querer decir", English = "MEAN,MEANT,MEANT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "helar,congelar", English = "FREEZE,FROZE,FROZEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "luchar", English = "FIGHT,FOUGHT,FOUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "encender", English = "LIGHT,LIT,LIT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "caer", English = "FALL,FELL,FALLEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "contar una historia", English = "TELL,TOLD,TOLD", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "correr", English = "RUN,RAN,RUN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "saber, conocer", English = "KNOW,KNEW,KNOWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "ocultar, esconder", English = "HIDE,HID,HIDDEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "perder", English = "LOSE,LOST,LOST", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "gastar", English = "SPEND,SPENT,SPENT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "oler", English = "SMELL,SMELT,SMELT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "estar,permanecer", English = "STAND,STOOD,STOOD", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "atrapar", English = "CATCH,CAUGHT,CAUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "oír", English = "HEAR,HEARD,HEARD", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "despertarse", English = "WAKE,WOKE,WOKEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "enviar", English = "SEND,SENT,SENT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "tirar", English = "THROW,THREW,THROWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "conocer,encontrarse", English = "MEET,MET,MET", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "barrer", English = "SWEEP,SWEPT,SWEPT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "soñar", English = "DREAM,DREAMT,DREAMT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "robar", English = "STEAL,STOLE,STOLEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "hablar", English = "SPEAK,SPOKE,SPOKEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "olvidar", English = "FORGET,FORGOT,FORGOTTEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "comprar", English = "BUY,BOUGHT,BOUGHT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "aprender", English = "LEARN,LEARNT,LEARNT", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "crecer", English = "GROW,GREW,GROWN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "volverse, llegar a ser", English = "BECOME,BECAME,BECOME", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "leer", English = "READ,READ,READ", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "comer", English = "EAT,ATE,EATEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "conducir", English = "DRIVE,DROVE,DRIVEN", GroupType = GroupType.IregularVerbs });
            list.Add(new Word { Spanish = "going well", English = "My new job schedule has really worked out for me.", GroupType = GroupType.PhrasalVerbs });
            list.Add(new Word { Spanish = "espejo", English = "mirror", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "chimenea", English = "fireplace", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cepillo pelo", English = "hairbrush", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cocina", English = "kitchen", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "piso", English = "floor", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "alfombra", English = "rug", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sofá", English = "settee", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "dentífrico", English = "toothpaste", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "horno de microondas", English = "microwave oven", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "jabonera", English = "soap dish", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "bidet", English = "bidet", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "esponja", English = "sponge", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "televisor", English = "television", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "jarra para café", English = "coffeepot", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "edredón", English = "duvet", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sartén", English = "frying pan", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "vaso", English = "glass", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "buzón", English = "letter box", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "grifo", English = "tap", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "lavadora", English = "washing machine", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "timbre", English = "doorbell", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "bol", English = "bowl", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "departamento", English = "flat", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "manta", English = "blanket", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "reloj despertador", English = "alarm clock", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "afeitadora", English = "safety razor", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "salón", English = "living room", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cuchara", English = "spoon", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "lavavajillas", English = "dishwasher", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "bañera", English = "bath", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "tenedor", English = "fork", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "mantel", English = "tablecloth", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "afeitadora eléctrica", English = "electric razor", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "batidora", English = "mixer", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "tabla de planchar", English = "ironing board", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "plato", English = "saucer", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "pileta", English = "sink", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "servilleta", English = "napkin", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "lavabo, lavatorio", English = "washbasin", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "abrelatas", English = "tin opener", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "estudio", English = "study", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "chimenea", English = "chimney", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cepillo de dientes", English = "toothbrush", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "horno", English = "oven", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cucharita", English = "teaspoon", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cuchillo", English = "knife", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "olla", English = "saucepan", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "luz", English = "light", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "colcha", English = "bedspread", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "colchón", English = "mattress", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sisterna", English = "toilet", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "secador de pelo", English = "hair drier", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "dormitorio", English = "bedroom", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "escaleras", English = "stairs", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "lámpara", English = "lamp", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "mesita de luz", English = "bedside table", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sotano, bodega", English = "cellar", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "peine", English = "comb", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cortina", English = "curtain", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "toalla", English = "towel", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sábana", English = "sheet", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "garaje", English = "garage", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sala de estar", English = "sitting room", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "puerta", English = "door", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "tostadora", English = "toaster", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sótano", English = "basement", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "licuadora", English = "liquidizer", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "ventana", English = "window", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "guardarropas", English = "wardrobe", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "comedor", English = "dining room", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "habitación", English = "room", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "silla", English = "chair", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "escoba", English = "broom", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "toallero", English = "towel rail", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "pared", English = "wall", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "crema de afeitar", English = "shaving foam", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "ático", English = "attic", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "balcón", English = "balcony", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "jabón", English = "soap", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "alfombra fija", English = "carpet", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "champú", English = "shampoo", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "jarra", English = "jug", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "papel higiénico", English = "toilet paper", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "cafetera", English = "coffee maker", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "techo", English = "ceiling", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "ducha", English = "shower", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "mesa", English = "table", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "techo", English = "roof", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "heladera", English = "fridge", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "olla a presión", English = "pressure cooker", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "papel de pared", English = "wallpaper", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "baño", English = "bathroom", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sillón", English = "armchair", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "caneca de basura", English = "waste bin", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "taza", English = "cup", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "sacacorchos", English = "corkscrew", GroupType = GroupType.House });
            list.Add(new Word { Spanish = "almohada", English = "pillow", GroupType = GroupType.House });

            foreach (var item in list)
            {
                if (!context.Words.Any(c => c.English.Equals(item.English) && c.GroupId == item.GroupId))
                {
                    context.Words.Add(item);
                }
            }

            context.SaveChanges();
        }
    }
}